### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by fishshiz** [fishshiz/tune-tent#1]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reduce
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by chungkikelly** [comment]
The sign-up form allows me to sign up with an existing username. Perhaps there's no uniqueness check?

**Comment by fishshiz** [comment]
I have both a db and model level unique validation. It works perfectly fine on local host. I just checked out Heroku and it seems like nothing is working for user auth. Do you have any ideas on what might cause something like this?
