### ISSUE TITLE
PA Review: Artist page

### ISSUE THREAD

**Issue by fishshiz** [fishshiz/tune-tent#3]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reduce
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by chungkikelly** [comment]
Need more seeding to demo the artist page.

**Comment by chungkikelly** [comment]
Will close for now, but please consider adding more realistic seed data when time permits.
